### ISSUE TITLE
When done, what is it doing?

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaMath/Infinities.jl#1]
I know people have wanted Integer with Infinity.

**Comment by dlfivefifty** [comment]
https://github.com/cjdoris/Infinity.jl/issues/25

**Comment by dlfivefifty** [comment]
Closing this in favour of https://github.com/JuliaMath/Infinities.jl/issues/2. @JeffreySarnoff  Any suggestions are of course appreciated. FYI we are doing Integers + Infinity as `InfExtendedInteger` as well as extended real lines, complex's, etc.
