### ISSUE TITLE
define `Base.one(::InfiniteCardinal)`

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaMath/Infinities.jl#3]
where there is `zero` it is nice to have `one`

**Comment by dlfivefifty** [comment]
Done.

**Comment by waldyrious** [comment]
[For the curious](https://github.com/JuliaMath/Infinities.jl/commit/e0704f801c58b0277307515d0367b54ecbe34103#diff-3dec9311ea4f2b07bd32d05f96345bad8a6ba2ad0d9918afa33c507cd871fa7fR32) :)
