### ISSUE TITLE
`Infinity` vs `RealInfinity()`

### ISSUE THREAD

**Issue by putianyi889** [JuliaMath/Infinities.jl#39]
The readme says 
> `∞` to represent the positive real infinity.
> `RealInfinity` to represent `±∞`.

Does that mean `∞` and `+∞` are the same thing?

**Comment by nsajko** [comment]
`∞` is `Infinity()`, where `Infinity` is the singleton type representing the positive real infinity.

`RealInfinity` is *not* a singleton type, the sign is determined by a field.
