### ISSUE TITLE
add `checked_mul`s

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaMath/Infinities.jl#4]
if `checked_add` is used by someone, `checked_mul` is likely to be used as well

**Comment by dlfivefifty** [comment]
Done.

**Comment by waldyrious** [comment]
> Done.

[Link for the curious](https://github.com/JuliaMath/Infinities.jl/commit/e0704f801c58b0277307515d0367b54ecbe34103#diff-4f3bf3ac240cb9a01a6494322478eab66180a7101a2f25bf930536a24f57a559R410-R413) :)
