### ISSUE TITLE
Comparing `ℵ₀` and `∞`

### ISSUE THREAD

**Issue by putianyi889** [JuliaMath/Infinities.jl#41]
Does these mean `ℵ₀` is strictly greater than `∞` while they are also equal? What is the purpose behind it?

https://github.com/JuliaMath/Infinities.jl/blob/0972ead14abe0eee1218c6f5b2e244775bd9e4c8/test/test_cardinality.jl#L22
https://github.com/JuliaMath/Infinities.jl/blob/0972ead14abe0eee1218c6f5b2e244775bd9e4c8/test/test_cardinality.jl#L43
https://github.com/JuliaMath/Infinities.jl/blob/0972ead14abe0eee1218c6f5b2e244775bd9e4c8/test/test_cardinality.jl#L77-L78
https://github.com/JuliaLang/julia/blob/43d7f881f8e26eb4bb7ef3d6f84b378d28125325/base/promotion.jl#L532-L533

**Comment by dlfivefifty** [comment]
Where do you get "strictly greater than"?

**Comment by dlfivefifty** [comment]
It actually says "not strictly greater than"

**Comment by putianyi889** [comment]
because Julia base defines `min` and `max` as
```julia
min(x,y) = ifelse(y < x, y, x)
max(x,y) = ifelse(y < x, x, y)
```
so if `min(x,y) == min(y,x) == x` then `x` must be strictly less.

**Comment by putianyi889** [comment]
It's because of promotion
```julia
min(x::Real, y::Real) = min(promote(x,y)...) # promotion.jl
```
