### ISSUE TITLE
Should `convert(::Type{<:InfiniteCardinal}, x) = convert(Integer, x)`?

### ISSUE THREAD

**Issue by LilithHafner** [JuliaMath/Infinities.jl#43]
I think that adding `convert(::Type{<:InfiniteCardinal}, x) = convert(Integer, x)` would allow `Base.OneTo(ℵ₀)` to replace `OneToInf()`, and also allow us to delete all `zero`/`one`/`oneunit` specializations, and possibly more.

This is dubious because `convert(T, x)` has a docstring that says `Convert x to a value of type T`, but `InfiniteCardinal` is an `Integer`, so this is close.

_Originally posted by @LilithHafner in https://github.com/JuliaMath/Infinities.jl/pull/42#discussion_r1262943926_

**Comment by vtjnash** [comment]
as posted before:

> No that isn't valid as convert(T, x) must return an element of type T

**Comment by dlfivefifty** [comment]
Use ` Base.oneto ` and InfiniteArrays.jl which support ∞
